spring:
  application:
    name: service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/student_management?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate.format_sql: true
server:
  servlet:
    context-path: /api
  port: 1122