import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: '/departments', pathMatch: 'full' },
  { path: 'about', loadComponent: () => import('./features/about/about.component').then(m => m.AboutComponent) },
  { path: 'departments', loadComponent: () => import('./features/departments/department-list/department-list.component').then(m => m.DepartmentListComponent) },
  { path: 'departments/new', loadComponent: () => import('./features/departments/department-form/department-form.component').then(m => m.DepartmentFormComponent) },
  { path: 'departments/:id/edit', loadComponent: () => import('./features/departments/department-form/department-form.component').then(m => m.DepartmentFormComponent) },
  { path: 'classes', loadComponent: () => import('./features/classes/class-list/class-list.component').then(m => m.ClassListComponent) },
  { path: 'classes/new', loadComponent: () => import('./features/classes/class-form/class-form.component').then(m => m.ClassFormComponent) },
  { path: 'classes/:id/edit', loadComponent: () => import('./features/classes/class-form/class-form.component').then(m => m.ClassFormComponent) },
  { path: 'students', loadComponent: () => import('./features/students/student-list/student-list.component').then(m => m.StudentListComponent) },
  { path: 'students/new', loadComponent: () => import('./features/students/student-form/student-form.component').then(m => m.StudentFormComponent) },
  { path: 'students/:id/edit', loadComponent: () => import('./features/students/student-form/student-form.component').then(m => m.StudentFormComponent) },
  { path: 'students/:id/overview', loadComponent: () => import('./features/students/student-overview/student-overview.component').then(m => m.StudentOverviewComponent) },
  { path: 'students/import', loadComponent: () => import('./features/students/student-import/student-import.component').then(m => m.StudentImportComponent) },
  { path: 'students/external', loadComponent: () => import('./features/students/external-students/external-students.component').then(m => m.ExternalStudentsComponent) },
  { path: 'academic-tree', loadComponent: () => import('./features/academic-tree/academic-tree.component').then(m => m.AcademicTreeComponent) },
  { path: 'reports/export', loadComponent: () => import('./features/reports/report-export/report-export.component').then(m => m.ReportExportComponent) },
  { path: 'subjects', loadComponent: () => import('./features/subjects/subject-list/subject-list.component').then(m => m.SubjectListComponent) },
  { path: 'subjects/new', loadComponent: () => import('./features/subjects/subject-form/subject-form.component').then(m => m.SubjectFormComponent) },
  { path: 'subjects/:id/edit', loadComponent: () => import('./features/subjects/subject-form/subject-form.component').then(m => m.SubjectFormComponent) },
  { path: 'semesters', loadComponent: () => import('./features/semesters/semester-list/semester-list.component').then(m => m.SemesterListComponent) },
  { path: 'semesters/new', loadComponent: () => import('./features/semesters/semester-form/semester-form.component').then(m => m.SemesterFormComponent) },
  { path: 'semesters/:id/edit', loadComponent: () => import('./features/semesters/semester-form/semester-form.component').then(m => m.SemesterFormComponent) },
  { path: 'lecturers', loadComponent: () => import('./features/lecturers/lecturer-list/lecturer-list.component').then(m => m.LecturerListComponent) },
  { path: 'lecturers/new', loadComponent: () => import('./features/lecturers/lecturer-form/lecturer-form.component').then(m => m.LecturerFormComponent) },
  { path: 'lecturers/:id/edit', loadComponent: () => import('./features/lecturers/lecturer-form/lecturer-form.component').then(m => m.LecturerFormComponent) },
  { path: 'rooms', loadComponent: () => import('./features/rooms/room-list/room-list.component').then(m => m.RoomListComponent) },
  { path: 'rooms/new', loadComponent: () => import('./features/rooms/room-form/room-form.component').then(m => m.RoomFormComponent) },
  { path: 'rooms/:id/edit', loadComponent: () => import('./features/rooms/room-form/room-form.component').then(m => m.RoomFormComponent) },
  { path: 'course-classes', loadComponent: () => import('./features/course-classes/course-class-list/course-class-list.component').then(m => m.CourseClassListComponent) },
  { path: 'course-classes/new', loadComponent: () => import('./features/course-classes/course-class-form/course-class-form.component').then(m => m.CourseClassFormComponent) },
  { path: 'course-classes/:id/edit', loadComponent: () => import('./features/course-classes/course-class-form/course-class-form.component').then(m => m.CourseClassFormComponent) },
  { path: 'schedules', loadComponent: () => import('./features/schedules/schedule-list/schedule-list.component').then(m => m.ScheduleListComponent) },
  { path: 'schedules/new', loadComponent: () => import('./features/schedules/schedule-form/schedule-form.component').then(m => m.ScheduleFormComponent) },
  { path: 'schedules/:id/edit', loadComponent: () => import('./features/schedules/schedule-form/schedule-form.component').then(m => m.ScheduleFormComponent) },
  { path: 'scores', loadComponent: () => import('./features/scores/score-list/score-list.component').then(m => m.ScoreListComponent) },
  { path: 'scores/new', loadComponent: () => import('./features/scores/score-form/score-form.component').then(m => m.ScoreFormComponent) },
  { path: 'scores/:id/edit', loadComponent: () => import('./features/scores/score-form/score-form.component').then(m => m.ScoreFormComponent) },
];
